### ISSUE TITLE
UI bug Ingest / Edit ORIGINAL Window has lost its close X button - very hard to cancel

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#10]
Platform Object: Create / ORIGINAL ReMake window
Expected Behaviour - click X in top right corner to close window
Current Behaviour: X button has been removed.
Current Workaround: escape button

note: the new behaviour where clicking outside of the window no longer closes the pop up is correct, thank you.
The X to close the window button is still required. 

<img width="1112" alt="image" src="https://github.com/think-jam/ReMake-Support/assets/148342500/377b0344-e0bc-44a4-a4a4-ae80ee918128">

**Comment by yasman-opstalent** [comment]
This ticket is not an issue but a necessary improvement.

The X button was never in the code, previously the modal was closed by clicking outside the modal, but in this task the behavior was changed:
https://trello.com/c/w8WX4IFX/2004-improvement-do-not-hide-edit-original-modal-if-the-user-you-accidentaly-clicks-outside-the-modal

**Comment by humberto0519** [comment]
**PR**:
[Link to PR](https://github.com/think-jam/vid-gen-react-components/pull/1581)
