### ISSUE TITLE
UI bug (not urgent): After uploading assets, the select AE/PSD/INDD window returns

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#11]
Platform process: ingesting AfterEffects
Current Behaviour: files upload then the pop up window returns to the select AE or PSD or INDD window.
Expected Behaviour: proceed straight to next window

User can still click through to next window, but clienys could be confused by this

<img width="465" alt="image" src="https://github.com/think-jam/ReMake-Support/assets/148342500/92565e1c-4f4a-452a-93a6-3b6554748273">

**Comment by yasman-opstalent** [comment]
This doesn't seem to happen for a while.
