### ISSUE TITLE
UI Bug: Image replacement not working on AE.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [think-jam/ReMake-Support#16]
Replacing an image layer on after effects does not update the translation object with the new url. Updating with this new image sends the object in translation empty, resulting in the update not happening.

## Expected
Uploading a new image should update the translation object with the updated value for this layer.

**Comment by tristan-remake** [comment]
Replacing any image layer is not updating / replacing. The same file is still displayed / rendered
expected
swapping an image should show the new image
This is urgent as it is the main functionality of the site!

**Comment by yasman-opstalent** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/0bca8de6-7743-4b82-b95b-c8d0431a7781)

**Comment by yasman-opstalent** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/16fb348d-ec7a-4fe7-8588-b7223c5e150f)
