### ISSUE TITLE
It's not possible to create a Video ReMake

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#17]
### Current Behavior

The request to the API to create a new Video ReMake is not answering.

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/08f975bf-ad27-413b-88f8-a4b6b7bd2194)

### Expected Behavior

The request is working as usual.

**Comment by yasman-opstalent** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/f89d2cca-bca0-4657-a8b4-349646c0b116)

**Comment by yasman-opstalent** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/f7f1653e-b9f1-4f52-8384-0d07bfa420b8)

**Comment by andyglez96** [comment]
![photo_2024-02-22_14-21-07](https://github.com/think-jam/ReMake-Support/assets/88163491/5f7adc84-d8d9-4773-b4d3-dae1bd099603)

**Comment by yasman-opstalent** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/afeff68f-585f-4a82-8ec5-a41329be208d)
