### ISSUE TITLE
Drag and Drop is allowed to upload images even though for users that are not allowed to upload files from the PC

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#19]
### Current Behavior

The permission to do not upload files from PC is hidding the link to upload from PC but it's allowing anyway the drag and drop option.

https://github.com/think-jam/ReMake-Support/assets/118522073/8c706e0d-be6b-4f47-8b24-2d69ab089e93

### Expected Behavior

Users with a role that containg a permission denied to upload from PC do not get the link to upload from PC and also are not able to drag and drop files from PC.

**Comment by humberto0519** [comment]
### Places to drag and drop file

- Edit video remake.
