### ISSUE TITLE
Static image disappears after an update

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#20]
### Current Behavior

Preview for Static ReMakes desappears after clicking on the Update button.

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/9d336f2e-b364-4944-b150-83c7efddb95a)

### Expected Behavior

The preview stays visible after updating a Static ReMake.

**Comment by yasman-opstalent** [comment]
When the preview disappears, if I select the area with the mouse, the preview is displayed again:
[Statis Preview is not displayed after update.webm](https://github.com/think-jam/ReMake-Support/assets/118522073/e3bc0c61-b2cc-41f2-9fa6-f236ec6236a0)

**Comment by MikeCowler** [comment]
for me, the image returns under these conditions,

- change size of browser window
- refresh browser

It doesn't happen all the time 8/10 it fails to display

**Comment by MikeCowler** [comment]
Testing this further, I can do 20 updates one after another and 5 of them in a row will return an image updates and then it'll stop again. if I keep going, it will return a couple more image updates and then vanish again.

**Comment by yasman-opstalent** [comment]
The ReMake under analysis was removed:
[ReMake created in the campaign Readhouse temporary](https://app.remake.video/remake/65d7922dbf5c530021a00bfe/static-original/65d792857621d200133f8fec/edit/65d89a62d8805700f7ddd2a9)

It's necessary to provide a new incident to continue working on this support request.

**Comment by yasman-opstalent** [comment]
New asset for testing:
https://staging.remake.video/remake/65bbb523396ea40021c4ff18/static-original/65dc46ef1171d600138aef55/edit/65dc47b58fa8bb00214a92f8

**Comment by MikeCowler** [comment]
This new test asset can be found at Staging>Torchlight>MC>blank image error

**Comment by MikeCowler** [comment]
Please note, it doesn't give a blank image every time, but it does most of the time for me!

**Comment by humberto0519** [comment]
PR:

https://github.com/think-jam/vid-gen-react-components/pull/1497

**Comment by yasman-opstalent** [comment]
There are no more mentions/requests related to this issue after the fix done.
