### ISSUE TITLE
Just 1 render is not recognizing an Adobe font

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#28]
### Current Behavior

There is one Render node taken out of the 3 we have. This was taken out Saturday early morning by Luis because it would not accept new fonts and so rendering from that node was causing it to use the wrong font.

### Expected Behavior

The render node is turned on again and works like the other 2.

**Comment by andyglez96** [comment]
The font is already working in the remaining nexrender-worker
