### ISSUE TITLE
Indesign not ingesting

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#3]
### Current Behavior
An attempt is being made to ingest IND files that have been ingested in the past but are no longer ingested.

### Expected Behavior
IND files that have been ingested in the past are ingested.

**Comment by andyglez96** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/88163491/a12dc0a1-630b-4f52-9e98-e5b66e00e37d)
