### ISSUE TITLE
Audio layer not editable on ingets

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#30]
I have ingested this several times but the audio layer does not show up to be selected to be editable.
I have tried it as WAV and mp3

MT
AMAZON
ROADHOUSE
RDHS_2024_SPMotion_Clip_DoYouHaveInsurance_1x1_Subbed_PVBrand_en-US_BKST

I have also put the projevct in the asset library
Asset Library
My Assets
Campaign: ROADHOUSE (RDHS)

please advise

**Comment by yasman-opstalent** [comment]
Project ingested in TORCHLIGHT> https://app.remake.video/remake/65f2f33f8f4add0021859bb5


The project file is in TORCHLIGHT>AL>My Assets> Audio issues project

**Comment by tristan-remake** [comment]
yes?
And as you can see the AUDIO TRACK is not showing up as editable so it cannot be swapped

**Comment by tristan-remake** [comment]
Can you please help diagnose why the audio track is not being ingested?

**Comment by tristan-remake** [comment]
This project works, so it is looking like it is this specific project:
MT
AMAZON
Asset Library
My Assets
Campaign: ROADHOUSE (RDHS)
RDHS_2024_SPMotion_SoYouLikeToFight_Pre_OrganicSocialSquare_1x1_RM

Can you compare it to the other one please.

**Comment by andyglez96** [comment]
@tristan-remake somehow the audio file in the project was being recognized as disabled in the script, I just removed it from the timeline and added it again, and now it's working.

I have uploaded the corrected version to the AL: MT-> Amazon -> My Assets -> Campaign: ROADHOUSE (RDHS) -> RDHS_2024_SPMotion_Clip_DoYouHaveInsurance_1x1_Subbed_PVBrand_en-US_BKST_v2.

Let me know if that one works for you

**Comment by tristan-remake** [comment]
weird. 
ok I wil check
Thanks

**Comment by tristan-remake** [comment]
I just did the same to my project and it worked!

**Comment by tristan-remake** [comment]
thanks!
