### ISSUE TITLE
"Turn off Layer" in Statics not working

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#31]
Expected Behaviour:
Selecting "Turn off layer" checkbox should make the layer invisible in Preview

Current Behaviour:
Checkbox has no effect

<img width="1732" alt="TunOffLayerSwitchNotWorking" src="https://github.com/think-jam/ReMake-Support/assets/148342500/77396848-f795-4b8b-9672-5489943d34df">
<img width="1792" alt="LeftPositionOnScreen" src="https://github.com/think-jam/ReMake-Support/assets/148342500/d6a1285a-6f44-4ee0-9baa-644aba6088c1">
<img width="1753" alt="LeftPositionOffScreen" src="https://github.com/think-jam/ReMake-Support/assets/148342500/ef684ba7-c2ff-46e6-a83e-4d5609366e9b">
<img width="1732" alt="TunOffLayerSwitchNotWorking" src="https://github.com/think-jam/ReMake-Support/assets/148342500/f7782ac7-92c7-4b21-8530-37ebdd448a04">
<img width="1792" alt="LeftPositionOnScreen" src="https://github.com/think-jam/ReMake-Support/assets/148342500/861468a5-9435-4634-9a8d-13abca4cc94c">
<img width="1753" alt="LeftPositionOffScreen" src="https://github.com/think-jam/ReMake-Support/assets/148342500/5bf35601-bae7-4132-a3bf-f7c0c6ceb355">

**Comment by marianocu** [comment]
I checked the issue and is solved 11/04/2024. I was not able to reproduce the issue. 
![image](https://github.com/think-jam/ReMake-Support/assets/54583932/931870c4-eb96-469f-b64f-ba20bce9c835)

**Comment by yasman-opstalent** [comment]
This doesn't seem to happen for a while.
