### ISSUE TITLE
URGENT: Cannot ingest simple file into King Campaign

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#32]
![image](https://github.com/think-jam/ReMake-Support/assets/148342500/c1c77148-f88a-4289-bb5f-579dbd6778b4)
Very simple project, like all King Projects
one mp4, one mov
Ae v23
<img width="1328" alt="Screenshot 2024-03-19 at 11 14 44" src="https://github.com/think-jam/ReMake-Support/assets/148342500/4c85b4c5-89d9-4e67-a870-649ad57c9888">
client waiting

**Comment by tristan-remake** [comment]
Can I have a full list of normal letter character combinations that I can no longert use in filenames then please?

**Comment by lazaroofarrill-opstalent** [comment]
At the moment file names can use any ASCII text combination excluding repetitions of the letters 'C', 'c'.
