### ISSUE TITLE
Unable to set static embargo in an original in MT / AMAZON  / ROADHOUSERDHS_2024_SPStatic_TomorrowCountdown_Pre_OrganicSocialSquare_1x1_Final_PRDSC

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#35]
Unable to set static embargo in an original in MT / AMAZON  / ROADHOUSERDHS_2024_SPStatic_TomorrowCountdown_Pre_OrganicSocialSquare_1x1_Final_PRDSC

In the Campaign tab turning it on isn't working.

 In the Original Images page it turns on , but when I go in to the Campaign it is off again

**Comment by marianocu** [comment]
This feature set embargo y working good.

**Comment by yasman-opstalent** [comment]
This doesn't seem to happen anymore.
