### ISSUE TITLE
Toggling visibility for image layer in video remakes breaks renders.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [think-jam/ReMake-Support#36]
When changing the visibility of an image layer the render fails.

The error thrown during render is the following one.
```js
aerender ERROR: Error executing script: C:\nexrender\workdir\7jQ8oK_fs11CHB3kH8drk\nexrender-7jQ8oK_fs11CHB3kH8drk-script.jsx
ReferenceError: o is undefined
aerender ERROR: Runtime error in After Effects
```

Thi original can be used to replicate the issue. [https://app.remake.video/original/66018cd4710bc8001306e0e9?sort=desc&sortBy=_id&assigned=false](https://app.remake.video/original/66018cd4710bc8001306e0e9?sort=desc&sortBy=_id&assigned=false).

**Comment by lazaroofarrill-opstalent** [comment]
Need to ingest the project locally to be able to debug the failure point in the script.

**Comment by yasman-opstalent** [comment]
This issue is not happening anymore.
