### ISSUE TITLE
Arabic SRTs are not translating ALL their subtitles

### ISSUE THREAD

**Issue by tristan-remake** [think-jam/ReMake-Support#38]
Tristan Summers

it is always the same SRT numbers 7, 8 and 9 that do not translate. - it also does not set the font for these three -
. you can duplicate this remake if you want to diagnose but please do not edit it as I have edited it

MT/Amazon/Roadhouse/RDHS_2024_Clip_FrankieExplainsTheName_9x16_Subbed_BKST_PVBrand
https://app.remake.video/remake/660d23ca163afb0013331655

srt and csv below

[RDHS_2024_Clip_FrankieExplainsTheName_Subbed_BKST_PVBrand.csv.zip](https://github.com/think-jam/ReMake-Support/files/14850256/RDHS_2024_Clip_FrankieExplainsTheName_Subbed_BKST_PVBrand.csv.zip)
[RDHS_2024_Trailer_Full_Clip23_FrankieExplainsTheName_FULLSRT_Finishing_ar-AE.srt.zip](https://github.com/think-jam/ReMake-Support/files/14850262/RDHS_2024_Trailer_Full_Clip23_FrankieExplainsTheName_FULLSRT_Finishing_ar-AE.srt.zip)

**Comment by MikeCowler** [comment]
Recreated this in MT>torchlight>torchlight_SRT>RDHS_2024_Clip_FrankieExplainsTheName_9x16_Subbed_SRT_TEST

**Comment by yasman-opstalent** [comment]
This issue was solved time ago.
