### ISSUE TITLE
1 to many does not render

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#39]
1 to many for this group has stopped working at some point. https://app.remake.video/campaign/62c6bf2ccc2f66001f3c6ccd

Each of them render individually.
i have deleted and recreated 1 to many groups with just one or two of the Originals in to see if it is down to one of them causing the problem but that testing doesn't point to a particular original causing the issue.
I have only selected text layers to edit and still causes the issue.
![image](https://github.com/think-jam/ReMake-Support/assets/76961733/a705a6be-256a-483d-9c31-b635f54d88dc)

(https://think-jam-workspace.slack.com/archives/D05BTH4JZB9/p1713536961700629)
![image](https://github.com/think-jam/ReMake-Support/assets/76961733/004cb5c3-5e14-439f-a5a5-dfae9cc57483)
![image (1)](https://github.com/think-jam/ReMake-Support/assets/76961733/6383e4f2-f43f-462b-8d35-aab63ad07097)
![image](https://github.com/think-jam/ReMake-Support/assets/76961733/e0397bd6-8c57-42d1-9de6-472dadbb9412)

MT>DEMO>Smart Sync>Smal single txt layer
https://app.remake.video/remake/66227f3e7068bd0021124a9c

**Comment by lazaroofarrill-opstalent** [comment]
https://github.com/think-jam/vidgen-v1/pull/2108
