### ISSUE TITLE
ReMake rendered without audio

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#4]
### Current Behavior
The render is generating a video for a ReMake without audio.

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/e1187602-38c1-4d0b-96f7-2760170c4abd)

### Expected Behavior
The render generates a video as ussual with the related audio.

**Comment by andyglez96** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/88163491/8aa86ea6-2110-4798-ba43-3a43104a9b07)
