### ISSUE TITLE
CSV bulk processing not handling disable layers as required

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#40]
### Overview

User needs to be able to disable any text or image layer from CSV without putting in the image or text in the text column for that layer.

[DoorDash_BusyLives_16x9_6s_ENG_v2_y_matrix.csv](https://github.com/think-jam/ReMake-Support/files/15063358/DoorDash_BusyLives_16x9_6s_ENG_v2_y_matrix.csv)

**Comment by lazaroofarrill-opstalent** [comment]
https://github.com/think-jam/vidgen-v1/pull/2110

**Comment by yasman-opstalent** [comment]
The solution is not working with the provided CSV in the mentioned ReMake, please check:

[issue_40.csv](https://github.com/think-jam/ReMake-Support/files/15093874/issue_40.csv)

https://app.remake.video/original/661676f011a1e60013e0e59d/bulk-details/6628c8b197ae120013ae64b9

**Comment by lazaroofarrill-opstalent** [comment]
https://github.com/think-jam/vidgen-v1/pull/2114

**Comment by yasman-opstalent** [comment]
The improvement is not ready.

https://staging.remake.video/original/66278144e63547001381489f/bulk-details/662f6aa50a4cbc00138bbe72

[SephoraT01 (3).csv](https://github.com/think-jam/ReMake-Support/files/15147439/SephoraT01.3.csv)

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/2b0cd8d2-53bf-4747-ae94-3ec036663dc3)

**Comment by lazaroofarrill-opstalent** [comment]
https://github.com/think-jam/vidgen-v1/pull/2141
