### ISSUE TITLE
Static carousel -Only the first text layer edit gets updated

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#42]
With the Static Carousel found here DEMO>Static Carousel>Carousel X
https://app.remake.video/remake/6523cf6ed5c6580021e5dffa/static-original/6527ffba5f7da70013677f3e/edit/662783d52949d400212f47d9

Only the first text layer I choose gets updated in edit mode. It doesn't matter which text layer I choose, I can only update the one I choose first.

![image](https://github.com/think-jam/ReMake-Support/assets/76961733/97cdc57b-0265-44db-ac05-b041f21ed112)

**Comment by lazaroofarrill-opstalent** [comment]
@yasman-opstalent this looks like a frontend caching issue. All layers in the carousel are getting updated correctly.

**Comment by humberto0519** [comment]
**PR**:

[Link](https://github.com/think-jam/vid-gen-react-components/pull/1602)

**Comment by MikeCowler** [comment]
This is not on MT yet. Please advise

**Comment by MikeCowler** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/76961733/40451474-967a-4f68-9dd5-1ccee441b555)
This is not working for me on MT. I am in the same campaign and using the same carousel as Luis but not working.

**Comment by lazaroofarrill-opstalent** [comment]
@humberto0519 The current solution is not guaranteed to work in all browsers.

The browser is caching the img requests and a page refresh is needed to see the changes.

Suggestion: 
prevent image caching in the carrousel by appending a timestamp as a query parameter to the images.
Force image container reload when updating image. The image is not being requested again after clicking on update.
