### ISSUE TITLE
No comments are seen from Review & Approve when in Edit page

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#46]
When a ReMake is reviewed and comments are left, they do not show up in the 'Comments' section of Edit.

![image](https://github.com/think-jam/ReMake-Support/assets/76961733/de8cbcac-62c8-40a5-a935-81ca1bea0422)

**Comment by humberto0519** [comment]
**PR**:
[Link to PR](https://github.com/think-jam/vid-gen-react-components/pull/1607)

**Comment by marianocu** [comment]
Comments are correctly displayed in the remake edit view
![image](https://github.com/think-jam/ReMake-Support/assets/54583932/d3d243ad-7a66-4622-ab79-908f54f5c306)
