### ISSUE TITLE
Static & video does not swap image from Asset Library if 'upload from desktop' is off.

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#48]
Very Urgent issue.

If a role is setup to only swap images from asset library and has "Allow Upload from Desktop" disabled in role setting then when the user selects the asset from the asset library it never renders into the image. For video you get the toaster stating "We had a problem updating the video markers."

to replicate

choose a role and disable "Allow upload from desktop"

Then try and swap an image from asset library for video or a static.

**Comment by yasman-opstalent** [comment]
This issue was solved yesterday.
