### ISSUE TITLE
Cannot Duplicate a Static ReMake

### ISSUE THREAD

**Issue by MikeCowler** [think-jam/ReMake-Support#49]
Org: TAG>Lidl Spain
https://app.remake.video/campaign/6632415f7cbf1e00214cf528

It is not possible to duplicate a static REMAKE not original. This is reported by TAG.

You can replicate this on any Static in any org.

Steps to reproduce,
1. cretae static remake
2. from remake tile select 'duplicate'
3. modal pops up with broken thumbnail and error code 500

![image (4)](https://github.com/think-jam/ReMake-Support/assets/76961733/330b2396-830e-4294-be2d-3a4c7580bdf8)

**Comment by vestefano** [comment]
The error that is occurring when you want to duplicate a static remake is because the frontend is not correctly sending the id of the remake in the request it makes to the api

![image](https://github.com/think-jam/ReMake-Support/assets/62723718/04c51614-3f93-4991-9800-b37533169735)

**Comment by MikeCowler** [comment]
Can we get this fix applied to MT asap?

**Comment by marianocu** [comment]
The duplicate static original is working in Mt

**Comment by MikeCowler** [comment]
This is not working for me.

![image](https://github.com/think-jam/ReMake-Support/assets/76961733/ca489132-848c-4700-ab01-51c1ef6fe087)

**Comment by MikeCowler** [comment]
![image](https://github.com/think-jam/ReMake-Support/assets/76961733/756571fd-e6da-4d46-b45f-36557f17cf65)

**Comment by marianocu** [comment]
The issue still happening 
![image](https://github.com/think-jam/ReMake-Support/assets/54583932/d8c1eae5-d214-47ea-b974-a585a9161a99)
