### ISSUE TITLE
Permissions type issue

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#5]
### Current Behavior
The button to edit a Rendered ReMake is disabled in the preview modal, even though the user has the permission to edit a Video ReMake.

https://github.com/think-jam/ReMake-Support/assets/118522073/0422059b-c375-4269-a076-7b77b211721a

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/f0498233-bc0d-4614-89b1-703fc655568d)

### Expected Behavior
The button to edit a Rendered ReMake is disabled for users without the permission to edit a ReMake.

**Comment by yasman-opstalent** [comment]
@MikeCowler is this still happening?

**Comment by MikeCowler** [comment]
I cannot reproduce so we can close this.
