### ISSUE TITLE
InDesign project ingest never ends

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#50]
### Current behavior

An Indesign project is not ingesting.

[Relocations - Merchandising Memo Folder.zip](https://github.com/think-jam/ReMake-Support/files/15261791/Relocations.-.Merchandising.Memo.Folder.zip)

### Expected behavior

The Original Indesign is created in MT.

**Comment by lazaroofarrill-opstalent** [comment]
https://github.com/think-jam/vidgen-v1/pull/2142
