### ISSUE TITLE
Text layer font is not render properly

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#51]
### Current Behavior

A specific project is displayed properly the changes for the live preview in a text layer but it renders incorrectly the text layer font.

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/9d664cd8-b26a-4ce7-bb36-6861878f0d11)

https://app.remake.video/remake/6644ab37b07eca00210e9df7

### Expected Behavior

Live preview and render get the same font for the text layer.

**Comment by yasman-opstalent** [comment]
**Notes from Mike:**

"The very strange thing is, if I change font to a random and then change it back again it now picks up the right font in the render"
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/25ecfc41-07e5-48ea-b89c-3df527429bb2)

"When I create it shows this,"
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/0e235155-039d-49e1-96c9-b730d8e0178b)

"But not every time
So this is strange.
It's soemtimes working and sometimes not
Now I see two instances of the same font in the font list"
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/ba141fcc-55c3-46e8-82f2-6cc175793512)

"when I select one and look back, the other one disappears"
![image](https://github.com/think-jam/ReMake-Support/assets/118522073/881cc14c-6e5d-4db9-8420-5621500e6c89)

"My observations:
1. Seems like it works sometimes
2. the same font sometimes listed twice in the font list suggests some confusion between font weights"

**Comment by lazaroofarrill-opstalent** [comment]
@yasman-opstalent  The font file provided did not have the correct name. Font reinstalled in all render nodes.

**Comment by lazaroofarrill-opstalent** [comment]
@yasman-opstalent to be closed.

**Comment by yasman-opstalent** [comment]
@MikeCowler please confirm the issue is not happening.

**Comment by MikeCowler** [comment]
Fixed
