### ISSUE TITLE
Can't click cancel button of items in the queue when the renders are stuck in finishing up.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [think-jam/ReMake-Support#52]
<img width="376" alt="image" src="https://github.com/think-jam/ReMake-Support/assets/152889758/46c04d21-b4e2-4fec-9212-c79fbe897506">

**Comment by yasman-opstalent** [comment]
This issue is not happening after the last release to MT:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.22-10_34_52.webm](https://github.com/think-jam/ReMake-Support/assets/118522073/ab7639df-3bf0-4963-bce2-6c3c217e96d8)

**Comment by MikeCowler** [comment]
Is this still open?
