### ISSUE TITLE
AE project ingest crashes.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [think-jam/ReMake-Support#54]
Project
https://app.remake.video/asset-library?p=62de41125f3a4f2d983d7b07/664f5ad4e163d500210baa54/

This project gets the worker stuck during the ingest phase.

First ingest produce no output.
After changing the encoding to json file produced by afterEffectsService to UTF-8 manully. The output is the following.
```
[{"result":"FAILURE","data":"Exception: Cannot switch to URL 
```

**Comment by yasman-opstalent** [comment]
More information here:
https://github.com/think-jam/ReMake-Support/issues/55

**Comment by vestefano** [comment]
It was detected that the AE project has problems in subtitle layers number 8 and 22. When the AE script reaches these layers, an error is not generated from which we can obtain information, but the injest process never ends. These layers must be deleted and created again.

![image](https://github.com/think-jam/ReMake-Support/assets/62723718/35a45ebd-0067-4cd1-87af-55c61a7f1747)

**Comment by MikeCowler** [comment]
Being able to detect, report and stop it causing the worker to stop is the next step.

**Comment by MikeCowler** [comment]
The designer re-created the Subtitles and this ingested. This also reduced the file size of the project and there was a suspicion this project was corrupted.

The ReMake task here is to flag any anomaly like this at ingest and report the project is bad. ideally, identifying the layer(s) causing the issue.
