### ISSUE TITLE
Workers Get Stuck During the Ingest Process

### ISSUE THREAD

**Issue by vestefano** [think-jam/ReMake-Support#55]
An issue was encountered during the ingestion process with the project shared below. When running ingestion, workers get stuck and do not complete assigned tasks. This behavior blocks the workflow and causes significant delays in data processing.

**Expected Behavior:**
Workers are expected to process tasks without interruptions and complete the ingestion process efficiently.

**Observed Behavior:**
The workers get stuck during the ingestion process and do not complete the assigned tasks, which interrupts the workflow.

Please investigate and resolve this issue as soon as possible, as it is affecting the efficiency of our workflow.

File: [IDEA_2024_SPMotion_MeetTheCastFavScene_1x1_Subbed_BSTV_PVBrand_en-US folder (218 MB) Amazon AL MT](https://app.remake.video/asset-library?p=62de41125f3a4f2d983d7b07/664f5ad4e163d500210baa54/)

**Comment by yasman-opstalent** [comment]
Comment from Mike:

IDEA from Leigh, IDEA. Does not ingest and kills workers
https://app.remake.video/asset-library?p=62de41125f3a4f2d983d7b07/664f5ad4e163d500210baa54/

**Comment by yasman-opstalent** [comment]
A ticket for this issue was opened yesterday:
https://github.com/think-jam/ReMake-Support/issues/55
