### ISSUE TITLE
Project in the Amazon organization doesn't ingest

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#57]
### Current Behavior
Project "IDEA_2024_SPMotion_MeetTheCastFavScene_1x1_Subbed_BSTV_PVBrand_en-US
Adventures of GHOUL" does not ingest.

https://app.remake.video/asset-library?p=62de41125f3a4f2d983d7b07/65f9776cce5f1a002123d391/66454676293e6c002183101e/664fc2975024e00021188862/

**Comment by MikeCowler** [comment]
Being able to detect, report and stop it causing the worker to stop is the next step.
