### ISSUE TITLE
Bug: InDesign project approval either fails or takes too long.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [think-jam/ReMake-Support#6]
# Problem

Clicking on approve on an InDesign Remake fails.  Sometimes it shows a red toast message. After some time has passed the approval can succeed.

# Expected Behaviour 
When clicking on approve the project is ready to share immediately.

**Comment by yasman-opstalent** [comment]
@MikeCowler is this still happening?

**Comment by MikeCowler** [comment]
It doesn't seem to fail but it is taking a long time to approve after pressing the approve button. What is the process here that takes this amount of time?
