### ISSUE TITLE
ReMake from Encode organization is not rendering

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#7]
### Current Behavior
The ReMake fails when rending: https://staging.remake.video/remake/65840a1478206300130b6cef

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/d298732f-38d9-43ce-969f-97f9d8031f18)

### Expected Behavior
The ReMake renders successfully.

**Comment by lazaroofarrill-opstalent** [comment]
photo used for replacement not found on s3. The video renders just fine when uploading a different photo.
